### ISSUE TITLE
Padronização de nomes de funções e variáveis

### ISSUE THREAD

**Issue by dunossauro** [LiveDivulgador/Live-Divulgador#14]
Existe uma quebra de integridade conceitual no código de maneira geral.

Algumas funções são declaradas com snake case outras com camel case. Em python, por definição sempre usamos snake case para funções e variáveis. Embora isso não seja mandatório, precisamos definir qual usar no projeto

**Comment by TigaxMT** [comment]
Irei trocar todos os nomes de variáveis e funções para snake case

**Comment by TigaxMT** [comment]
Corrigido em 9a8d75ea1482d03f420840d7bfa5e7b2ef1f2410
